//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GcErpConnection.GCUserCheck {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GCUserCheck.SisIntegracionClimaSoap")]
    public interface SisIntegracionClimaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEstadoCuentaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteResponse ConsultaEstadoCuentaCliente(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEstadoCuentaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteResponse> ConsultaEstadoCuentaClienteAsync(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEstadoCuentaAcesor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorResponse ConsultaEstadoCuentaAcesor(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaEstadoCuentaAcesor", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorResponse> ConsultaEstadoCuentaAcesorAsync(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaInformacionArticulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ConsultaInformacionArticulosResponse ConsultaInformacionArticulos(GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaInformacionArticulos", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaInformacionArticulosResponse> ConsultaInformacionArticulosAsync(GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaInformacionCotizacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionResponse ConsultaInformacionCotizacion(GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaInformacionCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionResponse> ConsultaInformacionCotizacionAsync(GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ProcesarPedidoResponse ProcesarPedido(GcErpConnection.GCUserCheck.ProcesarPedidoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ProcesarPedidoResponse> ProcesarPedidoAsync(GcErpConnection.GCUserCheck.ProcesarPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GcErpConnection.GCUserCheck.ValidarUsuarioResponse ValidarUsuario(GcErpConnection.GCUserCheck.ValidarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ValidarUsuarioResponse> ValidarUsuarioAsync(GcErpConnection.GCUserCheck.ValidarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEstadoCuentaCliente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEstadoCuentaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string clienteERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clienteBMP;
        
        public ConsultaEstadoCuentaClienteRequest() {
        }
        
        public ConsultaEstadoCuentaClienteRequest(string compania, string clienteERP, string clienteBMP) {
            this.compania = compania;
            this.clienteERP = clienteERP;
            this.clienteBMP = clienteBMP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEstadoCuentaClienteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEstadoCuentaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ConsultaEstadoCuentaClienteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet valoresERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ConsultaEstadoCuentaClienteResponse() {
        }
        
        public ConsultaEstadoCuentaClienteResponse(bool ConsultaEstadoCuentaClienteResult, System.Data.DataSet valoresERP, string mensajeError) {
            this.ConsultaEstadoCuentaClienteResult = ConsultaEstadoCuentaClienteResult;
            this.valoresERP = valoresERP;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEstadoCuentaAcesor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEstadoCuentaAcesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string clienteERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clienteBMP;
        
        public ConsultaEstadoCuentaAcesorRequest() {
        }
        
        public ConsultaEstadoCuentaAcesorRequest(string compania, string clienteERP, string clienteBMP) {
            this.compania = compania;
            this.clienteERP = clienteERP;
            this.clienteBMP = clienteBMP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaEstadoCuentaAcesorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaEstadoCuentaAcesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ConsultaEstadoCuentaAcesorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet valoresERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ConsultaEstadoCuentaAcesorResponse() {
        }
        
        public ConsultaEstadoCuentaAcesorResponse(bool ConsultaEstadoCuentaAcesorResult, System.Data.DataSet valoresERP, string mensajeError) {
            this.ConsultaEstadoCuentaAcesorResult = ConsultaEstadoCuentaAcesorResult;
            this.valoresERP = valoresERP;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacionArticulos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaInformacionArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string codArticulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string departamento;
        
        public ConsultaInformacionArticulosRequest() {
        }
        
        public ConsultaInformacionArticulosRequest(string compania, string codArticulo, string departamento) {
            this.compania = compania;
            this.codArticulo = codArticulo;
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacionArticulosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaInformacionArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ConsultaInformacionArticulosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet valoresERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ConsultaInformacionArticulosResponse() {
        }
        
        public ConsultaInformacionArticulosResponse(bool ConsultaInformacionArticulosResult, System.Data.DataSet valoresERP, string mensajeError) {
            this.ConsultaInformacionArticulosResult = ConsultaInformacionArticulosResult;
            this.valoresERP = valoresERP;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacionCotizacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaInformacionCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cotizacionBMP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string clienteERP;
        
        public ConsultaInformacionCotizacionRequest() {
        }
        
        public ConsultaInformacionCotizacionRequest(string compania, string cotizacionBMP, string clienteERP) {
            this.compania = compania;
            this.cotizacionBMP = cotizacionBMP;
            this.clienteERP = clienteERP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacionCotizacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaInformacionCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ConsultaInformacionCotizacionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string estadoPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string factura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string estadoFactura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string mensajeError;
        
        public ConsultaInformacionCotizacionResponse() {
        }
        
        public ConsultaInformacionCotizacionResponse(bool ConsultaInformacionCotizacionResult, string pedido, string estadoPedido, string factura, string estadoFactura, string mensajeError) {
            this.ConsultaInformacionCotizacionResult = ConsultaInformacionCotizacionResult;
            this.pedido = pedido;
            this.estadoPedido = estadoPedido;
            this.factura = factura;
            this.estadoFactura = estadoFactura;
            this.mensajeError = mensajeError;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class pedidoLinea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numoroLineaField;
        
        private string tipoProductoBMPField;
        
        private string codigoArticuloERPField;
        
        private decimal cantidadField;
        
        private decimal precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int numoroLinea {
            get {
                return this.numoroLineaField;
            }
            set {
                this.numoroLineaField = value;
                this.RaisePropertyChanged("numoroLinea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoProductoBMP {
            get {
                return this.tipoProductoBMPField;
            }
            set {
                this.tipoProductoBMPField = value;
                this.RaisePropertyChanged("tipoProductoBMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoArticuloERP {
            get {
                return this.codigoArticuloERPField;
            }
            set {
                this.codigoArticuloERPField = value;
                this.RaisePropertyChanged("codigoArticuloERP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPedido", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcesarPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cotizacionBMP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string codDepartamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string clienteERP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string clienteBMP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string fechaAprobacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string usaurioBMP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string direccionCobro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GcErpConnection.GCUserCheck.pedidoLinea[] lineasPedido;
        
        public ProcesarPedidoRequest() {
        }
        
        public ProcesarPedidoRequest(string compania, string cotizacionBMP, string codDepartamento, string clienteERP, string clienteBMP, string fechaAprobacion, string usaurioBMP, string direccionCobro, GcErpConnection.GCUserCheck.pedidoLinea[] lineasPedido) {
            this.compania = compania;
            this.cotizacionBMP = cotizacionBMP;
            this.codDepartamento = codDepartamento;
            this.clienteERP = clienteERP;
            this.clienteBMP = clienteBMP;
            this.fechaAprobacion = fechaAprobacion;
            this.usaurioBMP = usaurioBMP;
            this.direccionCobro = direccionCobro;
            this.lineasPedido = lineasPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPedidoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcesarPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcesarPedidoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string estadoPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mensajeError;
        
        public ProcesarPedidoResponse() {
        }
        
        public ProcesarPedidoResponse(bool ProcesarPedidoResult, string pedido, string estadoPedido, string mensajeError) {
            this.ProcesarPedidoResult = ProcesarPedidoResult;
            this.pedido = pedido;
            this.estadoPedido = estadoPedido;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string compania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string contrasena;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(string compania, string usuario, string contrasena) {
            this.compania = compania;
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidarUsuarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool autenticado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(bool ValidarUsuarioResult, bool autenticado, string mensajeError) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
            this.autenticado = autenticado;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SisIntegracionClimaSoapChannel : GcErpConnection.GCUserCheck.SisIntegracionClimaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SisIntegracionClimaSoapClient : System.ServiceModel.ClientBase<GcErpConnection.GCUserCheck.SisIntegracionClimaSoap>, GcErpConnection.GCUserCheck.SisIntegracionClimaSoap {
        
        public SisIntegracionClimaSoapClient() {
        }
        
        public SisIntegracionClimaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SisIntegracionClimaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisIntegracionClimaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SisIntegracionClimaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ConsultaEstadoCuentaCliente(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest request) {
            return base.Channel.ConsultaEstadoCuentaCliente(request);
        }
        
        public bool ConsultaEstadoCuentaCliente(string compania, string clienteERP, string clienteBMP, out System.Data.DataSet valoresERP, out string mensajeError) {
            GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest inValue = new GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest();
            inValue.compania = compania;
            inValue.clienteERP = clienteERP;
            inValue.clienteBMP = clienteBMP;
            GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ConsultaEstadoCuentaCliente(inValue);
            valoresERP = retVal.valoresERP;
            mensajeError = retVal.mensajeError;
            return retVal.ConsultaEstadoCuentaClienteResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteResponse> ConsultaEstadoCuentaClienteAsync(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaClienteRequest request) {
            return base.Channel.ConsultaEstadoCuentaClienteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ConsultaEstadoCuentaAcesor(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest request) {
            return base.Channel.ConsultaEstadoCuentaAcesor(request);
        }
        
        public bool ConsultaEstadoCuentaAcesor(string compania, string clienteERP, string clienteBMP, out System.Data.DataSet valoresERP, out string mensajeError) {
            GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest inValue = new GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest();
            inValue.compania = compania;
            inValue.clienteERP = clienteERP;
            inValue.clienteBMP = clienteBMP;
            GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ConsultaEstadoCuentaAcesor(inValue);
            valoresERP = retVal.valoresERP;
            mensajeError = retVal.mensajeError;
            return retVal.ConsultaEstadoCuentaAcesorResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorResponse> ConsultaEstadoCuentaAcesorAsync(GcErpConnection.GCUserCheck.ConsultaEstadoCuentaAcesorRequest request) {
            return base.Channel.ConsultaEstadoCuentaAcesorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ConsultaInformacionArticulosResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ConsultaInformacionArticulos(GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest request) {
            return base.Channel.ConsultaInformacionArticulos(request);
        }
        
        public bool ConsultaInformacionArticulos(string compania, string codArticulo, string departamento, out System.Data.DataSet valoresERP, out string mensajeError) {
            GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest inValue = new GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest();
            inValue.compania = compania;
            inValue.codArticulo = codArticulo;
            inValue.departamento = departamento;
            GcErpConnection.GCUserCheck.ConsultaInformacionArticulosResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ConsultaInformacionArticulos(inValue);
            valoresERP = retVal.valoresERP;
            mensajeError = retVal.mensajeError;
            return retVal.ConsultaInformacionArticulosResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaInformacionArticulosResponse> ConsultaInformacionArticulosAsync(GcErpConnection.GCUserCheck.ConsultaInformacionArticulosRequest request) {
            return base.Channel.ConsultaInformacionArticulosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ConsultaInformacionCotizacion(GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest request) {
            return base.Channel.ConsultaInformacionCotizacion(request);
        }
        
        public bool ConsultaInformacionCotizacion(string compania, string cotizacionBMP, string clienteERP, out string pedido, out string estadoPedido, out string factura, out string estadoFactura, out string mensajeError) {
            GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest inValue = new GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest();
            inValue.compania = compania;
            inValue.cotizacionBMP = cotizacionBMP;
            inValue.clienteERP = clienteERP;
            GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ConsultaInformacionCotizacion(inValue);
            pedido = retVal.pedido;
            estadoPedido = retVal.estadoPedido;
            factura = retVal.factura;
            estadoFactura = retVal.estadoFactura;
            mensajeError = retVal.mensajeError;
            return retVal.ConsultaInformacionCotizacionResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionResponse> ConsultaInformacionCotizacionAsync(GcErpConnection.GCUserCheck.ConsultaInformacionCotizacionRequest request) {
            return base.Channel.ConsultaInformacionCotizacionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ProcesarPedidoResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ProcesarPedido(GcErpConnection.GCUserCheck.ProcesarPedidoRequest request) {
            return base.Channel.ProcesarPedido(request);
        }
        
        public bool ProcesarPedido(string compania, string cotizacionBMP, string codDepartamento, string clienteERP, string clienteBMP, string fechaAprobacion, string usaurioBMP, string direccionCobro, GcErpConnection.GCUserCheck.pedidoLinea[] lineasPedido, out string pedido, out string estadoPedido, out string mensajeError) {
            GcErpConnection.GCUserCheck.ProcesarPedidoRequest inValue = new GcErpConnection.GCUserCheck.ProcesarPedidoRequest();
            inValue.compania = compania;
            inValue.cotizacionBMP = cotizacionBMP;
            inValue.codDepartamento = codDepartamento;
            inValue.clienteERP = clienteERP;
            inValue.clienteBMP = clienteBMP;
            inValue.fechaAprobacion = fechaAprobacion;
            inValue.usaurioBMP = usaurioBMP;
            inValue.direccionCobro = direccionCobro;
            inValue.lineasPedido = lineasPedido;
            GcErpConnection.GCUserCheck.ProcesarPedidoResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ProcesarPedido(inValue);
            pedido = retVal.pedido;
            estadoPedido = retVal.estadoPedido;
            mensajeError = retVal.mensajeError;
            return retVal.ProcesarPedidoResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ProcesarPedidoResponse> ProcesarPedidoAsync(GcErpConnection.GCUserCheck.ProcesarPedidoRequest request) {
            return base.Channel.ProcesarPedidoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GcErpConnection.GCUserCheck.ValidarUsuarioResponse GcErpConnection.GCUserCheck.SisIntegracionClimaSoap.ValidarUsuario(GcErpConnection.GCUserCheck.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public bool ValidarUsuario(string compania, string usuario, string contrasena, out bool autenticado, out string mensajeError) {
            GcErpConnection.GCUserCheck.ValidarUsuarioRequest inValue = new GcErpConnection.GCUserCheck.ValidarUsuarioRequest();
            inValue.compania = compania;
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            GcErpConnection.GCUserCheck.ValidarUsuarioResponse retVal = ((GcErpConnection.GCUserCheck.SisIntegracionClimaSoap)(this)).ValidarUsuario(inValue);
            autenticado = retVal.autenticado;
            mensajeError = retVal.mensajeError;
            return retVal.ValidarUsuarioResult;
        }
        
        public System.Threading.Tasks.Task<GcErpConnection.GCUserCheck.ValidarUsuarioResponse> ValidarUsuarioAsync(GcErpConnection.GCUserCheck.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
    }
}
